### PR TITLE
fix: build Linux x64 packages on Debian Buster for glibc 2.28

### LINKED ISSUE #2062: [Bug] x64 包 pty.node 依赖 glibc 2.35，在 RHEL 8 (glibc 2.28) 上闪退；建议 arm64 一样在 Debian Bullseye 容器内编译
### Operating system

Linux (RHEL 8 / CentOS 8, kernel 4.19.112-2.el8, glibc 2.28)

### Netcatty version

Latest x64 release (AppImage / deb / rpm all reproduce). Electron 42.3.3 / Chromium 148.

### How did you install Netcatty?

GitHub Release (.AppImage / .deb / .rpm)

### Affected area

Crash / app won't start

### Can you reproduce it?

Always (100%)

### Steps to reproduce

1. Install Netcatty x64 build on a glibc <= 2.30 system (e.g. RHEL 8 / CentOS 8 / UOS / Deepin)
2. Launch `netcatty`

### Expected behavior

Netcatty starts normally.

### Actual behavior

App crashes immediately on startup:

```
Uncaught exception: Error: Failed to load native module: pty.node, checked: build/Release, build/Debug, prebuilds/linux-x64: Error: Cannot find module './prebuilds/linux-x64//pty.node'
```

The error message is misleading — the file actually exists at `app.asar.unpacked/node_modules/node-pty/prebuilds/linux-x64/pty.node`. The real cause is a glibc symbol mismatch (`node-pty/lib/utils.js` catches the dlopen failure and rethrows as "Cannot find module"):

```
$ ldd .../prebuilds/linux-x64/pty.node
/lib64/libc.so.6: version `GLIBC_2.34' not found (required by pty.node)
/lib64/libc.so.6: version `GLIBC_2.32' not found (required by pty.node)
```

Root cause: `build-linux-x64` runs on `ubuntu-22.04` (glibc 2.35), so `electron-rebuild` links `pty.node` against glibc 2.35, incompatible with older distros.

The same repo's `build-linux-arm64` job already fixed this for arm64 by building inside a `debian:bullseye` (glibc 2.31) container, with a comment stating the intent:

> Dedicated job for Linux ARM64 — builds inside Debian Bullseye (GLIBC 2.31) to ensure compatibility with older distros like UOS/Deepin (GLIBC 2.28). Key: GLIBC < 2.34 avoids the libpthread-merge symbol requirement.

So arm64 was fixed (see #253), but x64 did not get the same containerized build, leaving the x64 package less compatible than arm64.

### Suggested fix

Align `build-linux-x64` with `build-linux-arm64`:

1. `runs-on: ubuntu-latest` + `container: image: debian:bullseye`
2. Replace `actions/setup-node` with an "Install build dependencies" step (nodesource setup_22.x + apt install build-essential python3 + Electron GUI runtime libs), mirroring the arm64 job
3. Keep the rest unchanged (`ensure-node-pty-linux.sh prepare x64`, `pack:linux-x64`)

Drops the built `pty.node` to glibc 2.31, covering RHEL 8 / UOS / Deepin, matching arm64 compatibility. For even broader coverage, `debian:buster` (glibc 2.28) aligns exactly with RHEL 8.

### Workaround

Replace `prebuilds/linux-x64/pty.node` with the one bundled in a local VS Code / Cursor install (node-pty 1.1.0-beta33, glibc 2.28, same exported symbols `PtyFork/Open/Resize/GetProc`) — Netcatty then starts normally.

### Before submitting

- [x] I searched existing issues and did not find a duplicate
- [x] I removed passwords, private keys, and other secrets from this report

### PR DESCRIPTION
**Pull request by binaricat**
## Summary
- Move `build-linux-x64` into a `debian:buster` container (glibc 2.28) so rebuilt `node-pty` / serialport natives load on RHEL 8, CentOS 8, UOS, and Deepin instead of requiring glibc 2.32–2.35 from ubuntu-22.04.
- Mirror the arm64 containerized install pattern: install build deps + Node inside the container (official Node 22 linux-x64 tarball, since NodeSource dropped Buster), keep prepare/pack/verify steps.
- Harden the archived-Buster apt path (`shell: bash`, `archive.debian.org`, `Acquire::Check-Valid-Until false`) and lock the container choice in workflow unit tests.

Fixes #2062

## Test plan
- [x] `node --test scripts/github-workflow-build.test.cjs`
- [x] Local `codex review --base main` (clean after bash + apt Valid-Until fixes)
- [ ] CI `build-linux-x64` job succeeds on this PR
- [ ] On a RHEL 8 / glibc ≤ 2.30 host, install the produced x64 package and confirm startup (no `GLIBC_2.3x not found` from `pty.node`)
- [ ] Optional: `ldd` / `objdump -T` on packaged `prebuilds/linux-x64/pty.node` shows max required GLIBC ≤ 2.28

### CODE REVIEW

**Comment by binaricat** [comment]
@codex review
