### ISSUE TITLE
[Bug] x64 包 pty.node 依赖 glibc 2.35，在 RHEL 8 (glibc 2.28) 上闪退；建议 arm64 一样在 Debian Bullseye 容器内编译

### ISSUE THREAD

**Issue by micookie2** [binaricat/Netcatty#2062]
### Operating system

Linux (RHEL 8 / CentOS 8, kernel 4.19.112-2.el8, glibc 2.28)

### Netcatty version

Latest x64 release (AppImage / deb / rpm all reproduce). Electron 42.3.3 / Chromium 148.

### How did you install Netcatty?

GitHub Release (.AppImage / .deb / .rpm)

### Affected area

Crash / app won't start

### Can you reproduce it?

Always (100%)

### Steps to reproduce

1. Install Netcatty x64 build on a glibc <= 2.30 system (e.g. RHEL 8 / CentOS 8 / UOS / Deepin)
2. Launch `netcatty`

### Expected behavior

Netcatty starts normally.

### Actual behavior

App crashes immediately on startup:

```
Uncaught exception: Error: Failed to load native module: pty.node, checked: build/Release, build/Debug, prebuilds/linux-x64: Error: Cannot find module './prebuilds/linux-x64//pty.node'
```

The error message is misleading — the file actually exists at `app.asar.unpacked/node_modules/node-pty/prebuilds/linux-x64/pty.node`. The real cause is a glibc symbol mismatch (`node-pty/lib/utils.js` catches the dlopen failure and rethrows as "Cannot find module"):

```
$ ldd .../prebuilds/linux-x64/pty.node
/lib64/libc.so.6: version `GLIBC_2.34' not found (required by pty.node)
/lib64/libc.so.6: version `GLIBC_2.32' not found (required by pty.node)
```

Root cause: `build-linux-x64` runs on `ubuntu-22.04` (glibc 2.35), so `electron-rebuild` links `pty.node` against glibc 2.35, incompatible with older distros.

The same repo's `build-linux-arm64` job already fixed this for arm64 by building inside a `debian:bullseye` (glibc 2.31) container, with a comment stating the intent:

> Dedicated job for Linux ARM64 — builds inside Debian Bullseye (GLIBC 2.31) to ensure compatibility with older distros like UOS/Deepin (GLIBC 2.28). Key: GLIBC < 2.34 avoids the libpthread-merge symbol requirement.

So arm64 was fixed (see #253), but x64 did not get the same containerized build, leaving the x64 package less compatible than arm64.

### Suggested fix

Align `build-linux-x64` with `build-linux-arm64`:

1. `runs-on: ubuntu-latest` + `container: image: debian:bullseye`
2. Replace `actions/setup-node` with an "Install build dependencies" step (nodesource setup_22.x + apt install build-essential python3 + Electron GUI runtime libs), mirroring the arm64 job
3. Keep the rest unchanged (`ensure-node-pty-linux.sh prepare x64`, `pack:linux-x64`)

Drops the built `pty.node` to glibc 2.31, covering RHEL 8 / UOS / Deepin, matching arm64 compatibility. For even broader coverage, `debian:buster` (glibc 2.28) aligns exactly with RHEL 8.

### Workaround

Replace `prebuilds/linux-x64/pty.node` with the one bundled in a local VS Code / Cursor install (node-pty 1.1.0-beta33, glibc 2.28, same exported symbols `PtyFork/Open/Resize/GetProc`) — Netcatty then starts normally.

### Before submitting

- [x] I searched existing issues and did not find a duplicate
- [x] I removed passwords, private keys, and other secrets from this report

**Comment by micookie2** [comment]
补充一个 glibc 边界细节，供选择容器镜像时参考：

`debian:bullseye` 是 glibc 2.31，**只能覆盖实际提供 `GLIBC_2.31` 符号的系统**。但部分 RHEL 8 / CentOS 8 派生系统（如本机）虽然 `ldd --version` 报 2.31，libc 实际只导出到 `GLIBC_2.30`：

```
$ ldd --version | head -1
ldd (GNU libc) 2.31
$ strings /lib64/libc.so.6 | grep -oE "GLIBC_[0-9.]+" | sort -V -u | tail -3
GLIBC_2.28
GLIBC_2.29
GLIBC_2.30
```

即"标称 2.31 但无 2.31 符号"。对这类系统，Bullseye (2.31) 编译的 `pty.node` 仍会因缺 `GLIBC_2.31` 而 dlopen 失败。

若要一并覆盖 RHEL 8 这类 2.28~2.30 系统，建议用 `debian:buster`（glibc 2.28）容器编译，产物只要求 `GLIBC_2.28`，兼容范围最广（RHEL 8 / CentOS 8 / UOS / Deepin 全覆盖）。

实测佐证：本机用 VS Code 自带的 node-pty（glibc 2.28 编译）替换后可正常启动，说明 2.28 基底足以兼容本机。
